version: '3.4'

services:
    mysql:
        image: mysql:5.7
        environment:
            MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
            MYSQL_DATABASE: app
            MYSQL_USER: app
            MYSQL_PASSWORD: app
        ports:
            - '13306:3306'
    fpm:
        build:
            context: .
            target: backend
        depends_on:
            - mysql
        environment:
            APP_ENV: dev
            DATABASE_URL: mysql://app:app@mysql:3306/app?serverVersion=5.7
        volumes:
            - .:/app:rw,cached
            - ./docker/php.dev.ini:/usr/local/etc/php/conf.d/application.ini:ro
    nginx:
        build:
            context: .
            target: frontend
        depends_on:
            - fpm
        volumes:
            - ./public:/app/public:ro
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
        ports:
            - '8000:80'
