# Контроллер авторизации
auth:
    path: /api/v1/auth
    controller: Free2er\Controller\AuthController

# Контроллер проверки работоспособности
ping:
    path: /api/v1/ping
    controller: Free2er\Controller\PingController
