parameters:
    locale: ru

services:
    _defaults:
        autowire: true
        autoconfigure: true

    # Контроллеры
    Free2er\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
